"""add consultations

Revision ID: 26591e3bcb9c
Revises: 42ca52eaceec
Create Date: 2026-09-17 16:33:52.458379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26591e3bcb9c'
down_revision: Union[str, Sequence[str], None] = '42ca52eaceec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='consultation_status'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_created_at'), 'consultations', ['created_at'], unique=False)
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index('ix_consultations_doctor_status_created', 'consultations', ['doctor_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index('ix_consultations_patient_status_created', 'consultations', ['patient_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_consultations_slot_id'), 'consultations', ['slot_id'], unique=True)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_index('ix_availability_doctor_booked_start', 'availability_slots', ['doctor_id', 'is_booked', 'start_time'], unique=False)
    op.create_index(op.f('ix_availability_slots_is_booked'), 'availability_slots', ['is_booked'], unique=False)
    op.create_index('ix_doctors_specialization_verified', 'doctors', ['specialization', 'is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctors_specialization_verified', table_name='doctors')
    op.drop_index(op.f('ix_availability_slots_is_booked'), table_name='availability_slots')
    op.drop_index('ix_availability_doctor_booked_start', table_name='availability_slots')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_slot_id'), table_name='consultations')
    op.drop_index('ix_consultations_patient_status_created', table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index('ix_consultations_doctor_status_created', table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_created_at'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
