"""add prescriptions

Revision ID: 9a8c2ac7f01f
Revises: 5214acb9b977
Create Date: 2026-09-24 13:28:17.032942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8c2ac7f01f'
down_revision: Union[str, Sequence[str], None] = '5214acb9b977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medicines', sa.String(length=2000), nullable=False),
    sa.Column('dosage', sa.String(length=500), nullable=False),
    sa.Column('frequency', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=True)
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index('ix_prescriptions_doctor_created', 'prescriptions', ['doctor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index('ix_prescriptions_patient_created', 'prescriptions', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_patient_created', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_doctor_created', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
